https://openclassrooms.com/fr/courses/7771531-decouvrez-les-librairies-python-pour-la-data-science/7856832-creez-vos-premiers-arrays-avec-numpy

# Manipulez les tableaux avec Numpy

In [16]:
!pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip


In [17]:
import numpy as np

revenus = [1800, 1500, 2200, 3000, 2172]
revenus_array = np.array(revenus)
revenus_array


array([1800, 1500, 2200, 3000, 2172])

Si dans la liste de départ il y a des données de types différents, NumPy essaiera de tous les convertir au type le plus général. Par exemple, si un tableau contient des entiers (  int  ) et des nombres décimaux (float ), tous ses éléments seront convertis en nombres décimaux (float ).

In [18]:
n, i, j, p = 3, 3, 3, 3

np.zeros(n) # permet de créer un array rempli de 0, de n éléments ;

np.ones(n) # similaire en tous points à la fonction présentée ci-dessus, à la différence que l’array sera rempli cette fois-ci de 1 ;

np.arange(i, j, p) # permet de créer un array rempli avec une séquence linéaire, qui ira de  i  à  j, par pas de  p  ;

np.linspace(i, j, n) # permet de créer un array de  n  valeurs espacées uniformément entre  i  et  j.

array([3., 3., 3.])

In [27]:
# array([1800, 1500, 2200, 3000, 2172])
revenus_array.dtype

dtype('int64')

Les types en NumPy seront toujours présentés via deux informations :

le type (ici  int  ) ;

la précision (ici  32  ).

Cette dernière correspond au nombre de bits sur lesquels sont codés les nombres, définissant ainsi les différentes valeurs possibles. Par exemple, un int8  (entier codé sur 8 bits) pourra prendre des valeurs de -128 à 127 !

#### On accède aux arrays comme on accède aux listes


In [20]:
# pour accéder au 5ème élement
revenus_array[4]

# On peut aussi modifier les valeurs
revenus_array[1] = 1900

In [21]:
# Séléctionne l'élément 0, 1, 2
revenus_array[0:3]

array([1800, 1900, 2200])

In [22]:
# Les 3 premiers éléments
print(revenus_array[:3])

[1800 1900 2200]


Nous pouvons accéder à un ensemble d'éléments contigus en combinant []  et  : . La syntaxe suit une règle simple : nom_array[i:j:p] , avec :

 i  : l’indice du début ;

 j  : l’indice de fin ;

p : le pas.

In [23]:
# Un élément sur deux
print(revenus_array[::2])

[1800 2200 2172]


In [24]:
# Si le pas est négatif, le début et la fin du slice sont inversés. On peut utiliser cette propriété pour inverser un tableau.
revenus_array[::-1]

array([2172, 3000, 2200, 1900, 1800])

# Accédez à plusieurs éléments selon une condition


nom_array[condition de sélection]

In [26]:
revenus_array[revenus_array > 2000]

array([2200, 3000, 2172])

In [34]:
revenus_array[(revenus_array > 500) & (revenus_array < 2800)]

array([1800, 1900, 2200, 2172])

#### Cela permet également de modifier des éléments au sein d'un array

In [36]:
revenus_array[revenus_array > 2000] = 0
revenus_array

array([1800, 1900,    0,    0,    0])

# Méthodes sur les arrays

In [37]:
revenus_array.shape
# (5,) on a array contenant 5 éléments

(5,)

In [38]:
# calculer la moyenne
revenus_array.mean()

np.float64(740.0)

In [43]:
# calculer la somme
revenus_array.sum()

np.int64(3700)

In [39]:
# calculer le maximum (ou le minimum) :
revenus_array.max()
revenus_array.min()

np.int64(0)

In [40]:
# accéder à l’indice de l’élement minimum (ou maximum) :
revenus_array.argmin()
revenus_array.argmax()

np.int64(1)

In [42]:
#ordonner les arrays
revenus_array.sort()
revenus_array

array([   0,    0,    0, 1800, 1900])

### En résumé pour les arrays

On peut sélectionner au sein d’un array :

un élément via son indice avec l’écriture : 

        nom_array[indice]  ;

plusieurs éléments contigus via la syntaxe : 

         nom_array[début:fin:pas]  ;

certains éléments spécifiques via une condition : 

        nom_array[condition]

# Tableaux numpy

In [44]:
# un tableau de 3x5 rempli de 1
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
# un tableau de 4 lignes et de 4 colonnes contenant que des 0
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
# un tableau de 3x3 rempli de valeurs aléatoires entières, comprises entre 1 et 10
np.random.randint(1, 10, size=(3, 3))

array([[3, 8, 3],
       [1, 7, 8],
       [7, 8, 7]])